ad= input("Adınızı giriniz: ")
soyad= input("Soyadınızı giriniz: ")
yas= input("Yaşınızı giriniz: ")
sehir= input("Yaşadığınız şehri giriniz: ")
meslek= input("Mesleğinizi giriniz: ")
print("="*40)
print("KİŞİSEL BİLGİLER")
print("="*40)
print(f"Adı-soyadı  : {ad} {soyad}")
print(f"Yaş         : {yas}")
print(f"Şehir       : {sehir}")
print(f"Meslek      : {meslek}")
print("="*40)